# Site
name: "IEEE-VIT"
description: "Official Blog of IEEE-VIT"
meta_description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/ieeevit-blue-1-5017x1103.png'
favicon: 'assets/images/logo.png'
baseurl: /ieeevitblog
google_analytics: 'UA-46278016-1'
#disqus: 'demowebsite'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

# Authors
authors:
  Shikha Jha:
    name: Shikha Jha
    display_name: Shikha Jha
    gravatar: ed67abe03c65a6f4b99e0099b881df8d
    email: 
    web: 
    twitter: https://twitter.com/
    description: "Webmaster 2018. Voyager Coordinator 2018 and Web Team Member Student Branch"
  Saurabh Fegade:
    name: Saurabh Fegade
    display_name: Saurabh Fegade
    gravatar: 66849570f3b4033d8c35600632f4237a
    email: 
    web: 
    twitter: https://twitter.com/
    description: "Webmaster 2018. Voyager Coordinator 2018 and Tech Team Member Student Branch"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge

theme: jekyll-theme-minimal